# Generated by Django 5.1 on 2024-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_list_delete_cart_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreat_user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='pin_code',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='pettreat_user',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
