# Generated by Django 5.1 on 2024-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pettreat_user_address_pettreat_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_weight', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
