# Generated by Django 5.1 on 2024-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_delete_cart_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_logos/')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('links', models.JSONField()),
                ('social_links', models.JSONField()),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
