# Generated by Django 5.1 on 2024-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_footer_delete_cart_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='navbar/')),
                ('links', models.JSONField()),
                ('profile_logo', models.ImageField(upload_to='navbar/')),
                ('cart_logo', models.ImageField(upload_to='navbar/')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
