# Generated by Django 5.1 on 2024-09-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_navbar_delete_cart_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
