# Generated by Django 5.1 on 2024-09-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_order_payment_method_delete_cart_new'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Cart_new',
    #     ),
    # ]
