# Generated by Django 5.1 on 2024-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_cart_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
