# Generated by Django 5.1 on 2024-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_is_canceled_delete_cart_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
