# Generated by Django 5.1 on 2024-09-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_quantity_delete_cart_new'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
