# Generated by Django 5.1 on 2024-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_cart_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        # migrations.DeleteModel(
        #     name='Cart_new',
        # ),
    ]
